import type { PartRevision, RevisionStatus } from "./model";

// 架空の評価用データ。業務ルールやAPIの正式な仕様を定義するものではない。
export const mockRevisions: PartRevision[] = [
  {
    id: "P-1001-3",
    partCode: "P-1001",
    name: "駆動シャフト",
    revision: 3,
    category: "駆動部品",
    material: "S45C",
    weight: 1.24,
    status: "申請中",
    effectiveDate: "2026-10-08",
    owner: "佐藤 美咲",
    updatedDate: "2026-10-01",
    changeReason: "加工工程の見直しに伴い、端部の形状と重量を変更。",
  },
  {
    id: "P-1002-2",
    partCode: "P-1002",
    name: "ベアリングハウジング",
    revision: 2,
    category: "支持部品",
    material: "ADC12",
    weight: 0.38,
    status: "適用中",
    effectiveDate: "2026-09-20",
    owner: "田中 健太",
    updatedDate: "2026-09-20",
    changeReason: "取り付け穴の公差を見直し、組み付け精度を改善。",
  },
  {
    id: "P-1003-1",
    partCode: "P-1003",
    name: "固定プレート",
    revision: 1,
    category: "支持部品",
    material: "SS400",
    weight: 2.85,
    status: "承認済",
    effectiveDate: "2026-10-03",
    owner: "鈴木 遥",
    updatedDate: "2026-09-30",
    changeReason: "新規設備向けの固定プレートを登録。",
  },
  {
    id: "P-1004-4",
    partCode: "P-1004",
    name: "搬送ローラー",
    revision: 4,
    category: "駆動部品",
    material: "SUS304",
    weight: 3.6,
    status: "下書き",
    effectiveDate: null,
    owner: "佐藤 美咲",
    updatedDate: "2026-10-01",
    changeReason: "耐食性向上のため、材質と表面処理を検討中。",
  },
  {
    id: "P-1005-2",
    partCode: "P-1005",
    name: "ガイドレール",
    revision: 2,
    category: "支持部品",
    material: "A6061",
    weight: 1.8,
    status: "適用中",
    effectiveDate: "2026-09-15",
    owner: "高橋 翔",
    updatedDate: "2026-09-15",
    changeReason: "搬送ストロークの変更に合わせて全長を変更。",
  },
  {
    id: "P-1006-3",
    partCode: "P-1006",
    name: "接続ブラケット",
    revision: 3,
    category: "締結部品",
    material: "SS400",
    weight: 0.65,
    status: "申請中",
    effectiveDate: "2026-10-10",
    owner: "田中 健太",
    updatedDate: "2026-09-30",
    changeReason: "接続位置の変更に伴い、取り付け穴を追加。",
  },
  {
    id: "P-1007-1",
    partCode: "P-1007",
    name: "保護カバー",
    revision: 1,
    category: "外装部品",
    material: "SUS304",
    weight: 0.42,
    status: "承認済",
    effectiveDate: "2026-10-05",
    owner: "鈴木 遥",
    updatedDate: "2026-09-29",
    changeReason: "安全対策として回転部の保護カバーを追加。",
  },
  {
    id: "P-1008-2",
    partCode: "P-1008",
    name: "六角スペーサー",
    revision: 2,
    category: "締結部品",
    material: "S45C",
    weight: 0.09,
    status: "適用中",
    effectiveDate: "2026-09-18",
    owner: "高橋 翔",
    updatedDate: "2026-09-18",
    changeReason: "組み付け時の高さ調整のため、寸法を変更。",
  },
  {
    id: "P-1009-1",
    partCode: "P-1009",
    name: "センサーマウント",
    revision: 1,
    category: "支持部品",
    material: "A6061",
    weight: 0.24,
    status: "下書き",
    effectiveDate: null,
    owner: "佐藤 美咲",
    updatedDate: "2026-09-29",
    changeReason: "位置検出センサーの新規取り付け部品を検討中。",
  },
  {
    id: "P-1010-2",
    partCode: "P-1010",
    name: "テンションアーム",
    revision: 2,
    category: "駆動部品",
    material: "S45C",
    weight: 1.56,
    status: "申請中",
    effectiveDate: "2026-10-12",
    owner: "高橋 翔",
    updatedDate: "2026-09-28",
    changeReason: "ベルト張力の調整範囲を拡大するため、形状を変更。",
  },
  {
    id: "P-1001-2",
    partCode: "P-1001",
    name: "駆動シャフト",
    revision: 2,
    category: "駆動部品",
    material: "S45C",
    weight: 1.32,
    status: "適用中",
    effectiveDate: "2026-09-10",
    owner: "佐藤 美咲",
    updatedDate: "2026-09-10",
    changeReason: "軸受けの変更に伴い、外径を調整。",
  },
  {
    id: "P-1006-2",
    partCode: "P-1006",
    name: "接続ブラケット",
    revision: 2,
    category: "締結部品",
    material: "SS400",
    weight: 0.68,
    status: "旧版",
    effectiveDate: "2026-08-22",
    owner: "田中 健太",
    updatedDate: "2026-09-01",
    changeReason: "旧設備用の接続ブラケット。現在は参照用として保管。",
  },
];

export const statusCount = (status: RevisionStatus) =>
  mockRevisions.filter((row) => row.status === status).length;
